<a href="https://colab.research.google.com/github/Imanur/datamining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [82]:
#importdataset 
#pemanggilan Dataset dengan nama Datanilaimhs.csv
dataset = pd.read_csv('DataMasak2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [83]:
print(x)

[['Wortel' 50.0 30000.0]
 ['Timun' 72.0 35000.0]
 ['Kubis' 12.0 20000.0]
 ['Brokoli' nan 18000.0]
 ['Tomat' 38.0 48000.0]
 ['Terong' 12.0 nan]
 ['Jengkol' 22.0 70000.0]
 ['Kacang' 55.0 25000.0]]


In [84]:
print(y)

['No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']


In [85]:
#Menghilangkan  missing value
from sklearn.impute import SimpleImputer
#missing values = nilai data yang digunakan sebagai penanda bahwa nilai aslinya tidak ada 
#strategy : menggunakan rata-rata kolom mean bisa juga menggunakan median, most_frequent(modus) atau constant
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [86]:
print(x)

[['Wortel' 50.0 30000.0]
 ['Timun' 72.0 35000.0]
 ['Kubis' 12.0 20000.0]
 ['Brokoli' 37.285714285714285 18000.0]
 ['Tomat' 38.0 48000.0]
 ['Terong' 12.0 35142.857142857145]
 ['Jengkol' 22.0 70000.0]
 ['Kacang' 55.0 25000.0]]


In [87]:
print(y)

['No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']


In [88]:
#Enconding Data kategori(Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [89]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 30000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 72.0 35000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 12.0 20000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 37.285714285714285 18000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 12.0 35142.857142857145]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 22.0 70000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.0 25000.0]]


In [90]:
#Encoding Data kategori(class/label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [91]:
print(y)

[0 1 1 0 1 0 0 1]


In [92]:
#Membagi dataset ke dalam training set dan test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [93]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 72.0 35000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 22.0 70000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 30000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 48000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 37.285714285714285 18000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 12.0 35142.857142857145]]


In [94]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.0 25000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 12.0 20000.0]]


In [95]:
print(y_train)

[1 0 0 1 0 0]


In [96]:
print(y_test)

[1 1]


In [97]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [98]:
print(x_train)

[[0.0 0.0 0.0 0.0 -0.44721359549995787 2.2360679774997894
  -0.44721359549995787 -0.44721359549995787 1.7349262410999888
  -0.2673117047916372]
 [0.0 1.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -0.8582019484444782
  1.8799462517313474]
 [0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 2.2360679774997894 0.5939498377004233
  -0.5740628414377779]
 [0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  2.2360679774997894 -0.44721359549995787 -0.02840092779024873
  0.5302412504883286]
 [1.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -0.0654456162123126
  -1.3102655693885155]
 [0.0 0.0 0.0 0.0 2.2360679774997894 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -1.3768275863533717
  -0.2585473866017473]]


In [99]:
print(x_test)

[[0.0 0.0 1.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 0.8532626566548701
  -0.8808139780839185]
 [0.0 0.0 0.0 1.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -1.3768275863533717
  -1.1875651147300592]]
